export const language = {
	en: {
		about: `About`,
		actions: `Actions`,
		addTopic: `Add topic`,
		addComment: `Add a comment`,
		amount: `Amount`,
		arBalance: `AR Balance`,
		arweaveAppUploadBlocked: `Arweave.app is not supported for upload`,
		assets: `Assets`,
		assetExists: `An asset with this name already exists`,
		assetFetchConnectionRequired: `Connect a wallet to view your assets`,
		assetTopics: `Asset topics`,
		assetLicenseCheck: `This asset will contain a license`,
		assetRights: `Asset Rights`,
		assetStamped: `Asset stamped`,
		assetUploaded: `Asset uploaded`,
		assetUploading: `Uploading Asset`,
		assetUploadingInfo: `Your assets are being uploaded, this will take some time. Please stay on this screen. Once all of the assets are uploaded, your collection will be created.`,
		back: `Back`,
		banner: `Banner`,
		bio: `Bio`,
		cancel: `Cancel`,
		calculating: `Calculating`,
		channel: `Channel`,
		channelDetails: `Channel details`,
		channelTitle: `Channel Title`,
		charLimitReached: `Character Limit Reached`,
		checks: `Checks`,
		chooseExistingAssets: `Choose existing assets`,
		clear: `Clear`,
		close: `Close`,
		collections: `Collections`,
		collectionCode: `Collection code`,
		collectionCodeInfo: `A collection code is a unique identifier for your collection. It can be used to identify which collection an asset belongs to in other applications.`,
		collectionCreated: `Collection created`,
		collectionDetails: `Collection details`,
		collectionExists: `A collection with this title already exists`,
		collectionUploadedInfo: `Your collection has been created ! You can view it directly in BazAR by clicking View collection below.`,
		comment: `Comment`,
		comments: `Comments`,
		community: `Community`,
		contentTokens: `Content tokens`,
		contentTokensInfo: `This balance will be assigned to each newly created asset.`,
		conversion: `Conversion`,
		connect: `Connect`,
		connectToContinue: `Connect your wallet to continue`,
		connectWallet: `Connect Wallet`,
		connectorNotFound: `Connector not found`,
		copied: `Copied`,
		copyURL: `Copy URL`,
		copyWalletAddress: `Copy wallet address`,
		createACollection: `Create a collection`,
		customAmount: `Custom Amount`,
		customAmountTurboInfo: `min $5 - max $10,000`,
		description: `Description`,
		details: `Details`,
		disconnect: `Disconnect`,
		dismiss: `Dismiss`,
		download: `Download`,
		downloading: `Downloading`,
		editDescription: `Edit description`,
		editProfile: `Edit profile`,
		editTitle: `Edit title`,
		errorOccurred: `Error occurred`,
		existingAssets: `Existing`,
		fetch: `Fetch`,
		fetching: `Fetching`,
		fileName: `Filename`,
		filesSelected: `Files selected`,
		follow: `Follow`,
		followed: (address: string) => `Followed ${address}`,
		follower: `Follower`,
		followers: `Followers`,
		following: `Following`,
		fullScreen: `Full screen`,
		fund: `Fund`,
		fundTurboBalance: `Fund Turbo Balance`,
		fundTurboBalanceInfoHeader: `Buy Credits`,
		fundTurboBalanceInfoDetail: `Credits will be automatically added to your Turbo balance, and you can start using them right away.`,
		fundTurboPaymentHeader: `Complete Payment`,
		fundTurboPaymentDetail: `In order to securely complete your payment, click Go to payment below. This will open a new window that will allow you to complete the purchase.`,
		goToPayment: `Go to payment`,
		handle: `Handle`,
		home: `Home`,
		insufficientBalance: `Insufficient Upload Balance`,
		invalidAmountTurbo: `Amount must be between $5 - $10,000`,
		invalidContentTokens: `Value must be between 0 - 1,000,000`,
		length: `Length`,
		license: `License`,
		licenseTags: {
			addTerms: `Add Terms`,
			access: {
				label: `Access Fee`,
				options: {
					none: `None`,
					oneTime: `One Time`,
				},
			},
			derivations: {
				label: `Derivations`,
				options: {
					disallowed: `Disallowed`,
					allowed: `Allowed`,
					suboptions: {
						credit: `With Credit`,
						indication: `With Indication`,
						licensePassthrough: `With License Passthrough`,
						revenueShare: `With Revenue Share`,
						monthlyFee: `With Monthly Fee`,
						oneTimeFee: `With One-Time Fee`,
					},
				},
			},
			commercialUse: {
				label: `Commercial Use`,
				options: {
					disallowed: `Disallowed`,
					allowed: `Allowed`,
					suboptions: {
						revenueShare: `With Revenue Share`,
						monthlyFee: `With Monthly Fee`,
						oneTimeFee: `With One-Time Fee`,
					},
				},
			},
			dataModelTraining: {
				label: `Data Model Training`,
				options: {
					disallowed: `Disallowed`,
					allowed: `Allowed`,
					suboptions: {
						monthlyFee: `With Monthly Fee`,
						oneTimeFee: `With One-Time Fee`,
					},
				},
			},
			paymentMode: {
				label: `Payment Mode`,
				single: `Single`,
				random: `Random`,
				global: `Global`,
			},
		},
		loading: `Loading`,
		max: `Max`,
		miniplayer: `Miniplayer`,
		mute: `Mute`,
		next: `Next`,
		noAssets: `No Assets`,
		noBio: `No Bio`,
		noCollections: `No collections`,
		noResults: `No Results`,
		pageNotFound: `Page Not Found`,
		pause: `Pause`,
		payLicense: `Pay License`,
		paymentInformation: `Payment`,
		play: `Play`,
		playingPiP: `Playing in picture-in-picture`,
		posted: `Posted`,
		postYourReply: `Post your reply`,
		previous: `Previous`,
		previewContent: `Preview content`,
		profile: `Profile`,
		profileCreated: `Profile created`,
		profileCreatedInfo: `Your profile has been created, welcome to Helix ! You can visit your profile directly by clicking View profile below.`,
		profileExists: `Profile Exists`,
		profileExistsInfo: `It looks like you already have an account ! You can visit your profile directly by clicking View profile below.`,
		profileUpdated: `Profile updated`,
		profileUpdatedInfo: `Your profile has been updated.`,
		recipient: `Recipient`,
		removeAvatar: `Remove avatar`,
		removeBanner: `Remove banner`,
		removeFile: `Remove file`,
		reply: `Reply`,
		returnToWindow: `Return to window`,
		save: `Save`,
		search: `Search`,
		select: `Select`,
		selectFiles: `Select files to upload`,
		showingAssets: `Showing assets`,
		showingFiles: `Showing files`,
		signUp: `Sign up`,
		signUpRequired: `Sign up required`,
		signUpRequiredInfo: `You must create an account to continue`,
		share: `Share`,
		shareOn: `Share on`,
		show: `Show`,
		size: `Size`,
		stamp: `Stamp`,
		stamped: `Stamped`,
		submit: `Submit`,
		successfullyFunded: `Successfully funded`,
		supportedFileTypes: `Any file type is supported for upload`,
		terms: `Terms`,
		title: `Title`,
		titleNotFound: `Title not found`,
		thumbnail: `Thumbnail`,
		thumbnailDescription: `Upload an image that represents your collection`,
		totalAssets: `Total`,
		topic: `Topic`,
		topics: `Topics`,
		topicInfo: `Topics will be attached to newly created assets`,
		toUpload: `To upload`,
		turboBalance: `Turbo Balance`,
		turboUploadCost: `Turbo upload cost`,
		udl: `Universal Data License`,
		unmute: `Unmute`,
		upload: `Upload`,
		uploading: `Uploading`,
		uploadAvatar: `Upload avatar`,
		uploadCost: `Upload cost`,
		uploadBanner: `Upload banner`,
		uploadConnectionRequired: `Wallet connection required to upload`,
		uploadChecksCostInfo: `Select a file to determine its upload cost`,
		uploadChecksCostTurboInfo: `Select Fetch to view your turbo balance`,
		uploadFiles: `Upload files`,
		uploadStatus: `Upload status`,
		uploadStepsInfo: `File Selected. Complete remaining steps to begin uploading`,
		uploadThumbnail: `Upload thumbnail`,
		uploadThumbnailInfo: `Pause the video at any point and click Upload to generate a thumbnail`,
		uploadingFileCount: (start: number, end: number) => `Uploading file: ${start} of ${end}`,
		useHandleForChannel: `Use Handle for Channel Title`,
		useScreenshot: `Use screenshot from content`,
		validating: `Validating`,
		video: `Video`,
		videos: `Videos`,
		viewAsset: `View Asset`,
		viewCollection: `View collection`,
		viewLicense: `View License`,
		viewOnBazar: `View on BazAR`,
		viewProfile: `View profile`,
		waitingToUpload: `Waiting to upload`,
		yourBalance: `Your balance`,
	},
};
