export const SET_UPLOAD = 'SET_UPLOAD';
export const SET_UPLOAD_ACTIVE = 'SET_UPLOAD_ACTIVE';
export const SET_STEP_DETAILS = 'SET_STEP_DETAILS';
export const SET_STEP_DISABLED = 'SET_STEP_DISABLED';
export const SET_UPLOAD_COST = 'SET_UPLOAD_COST';
export const SET_UPLOAD_DISABLED = 'SET_UPLOAD_DISABLED';
export const CLEAR_UPLOAD = 'CLEAR_UPLOAD';
